//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainVision.Lab.FileFormats.BrainProducts.GenericDataFormat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainVision.Lab.FileFormats.BrainProducts.GenericDataFormat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel info is incomplete:.
        /// </summary>
        internal static string ChannelInfoIncomplete {
            get {
                return ResourceManager.GetString("ChannelInfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel list doesn&apos;t match NumberOfChannels..
        /// </summary>
        internal static string ChannelInfosDoNotMatchNumberOfChannels {
            get {
                return ResourceManager.GetString("ChannelInfosDoNotMatchNumberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel info contains unrecognized surplus items:.
        /// </summary>
        internal static string ChannelInfoWithSurplusItems {
            get {
                return ResourceManager.GetString("ChannelInfoWithSurplusItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the coordinates cannot be parsed:.
        /// </summary>
        internal static string CoordinatesCannotBeParsed {
            get {
                return ResourceManager.GetString("CoordinatesCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates list doesn&apos;t match NumberOfChannels..
        /// </summary>
        internal static string CoordinatesDoNotMatchNumberOfChannels {
            get {
                return ResourceManager.GetString("CoordinatesDoNotMatchNumberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates are incomplete:.
        /// </summary>
        internal static string CoordinatesIncomplete {
            get {
                return ResourceManager.GetString("CoordinatesIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates contain unrecognized surplus items:.
        /// </summary>
        internal static string CoordinatesWithSurplusItems {
            get {
                return ResourceManager.GetString("CoordinatesWithSurplusItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated key:.
        /// </summary>
        internal static string DuplicatedKey {
            get {
                return ResourceManager.GetString("DuplicatedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated section:.
        /// </summary>
        internal static string DuplicatedSection {
            get {
                return ResourceManager.GetString("DuplicatedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be empty:.
        /// </summary>
        internal static string FileNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line. Expected key=keyValue syntax:.
        /// </summary>
        internal static string InvalidLine {
            get {
                return ResourceManager.GetString("InvalidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory key not found:.
        /// </summary>
        internal static string MandatoryKeyNotPresent {
            get {
                return ResourceManager.GetString("MandatoryKeyNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory section not found:.
        /// </summary>
        internal static string MandatorySectionNotPresent {
            get {
                return ResourceManager.GetString("MandatorySectionNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonconsecutive channel number:.
        /// </summary>
        internal static string NonConsecutiveChannelNumber {
            get {
                return ResourceManager.GetString("NonConsecutiveChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SegmentationType must not be NOTSEGMENTED..
        /// </summary>
        internal static string SegmentationTypeMustNotBeNotSegmented {
            get {
                return ResourceManager.GetString("SegmentationTypeMustNotBeNotSegmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content does not comply with the BrainVision Core Data format..
        /// </summary>
        internal static string StandardExceptionText {
            get {
                return ResourceManager.GetString("StandardExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file extension. Expected:.
        /// </summary>
        internal static string UnrecognizedFileExtension {
            get {
                return ResourceManager.GetString("UnrecognizedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized identification text. Expected:.
        /// </summary>
        internal static string UnrecognizedIdentificationText {
            get {
                return ResourceManager.GetString("UnrecognizedIdentificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized key:.
        /// </summary>
        internal static string UnrecognizedKey {
            get {
                return ResourceManager.GetString("UnrecognizedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized key value:.
        /// </summary>
        internal static string UnrecognizedKeyValue {
            get {
                return ResourceManager.GetString("UnrecognizedKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized section:.
        /// </summary>
        internal static string UnrecognizedSection {
            get {
                return ResourceManager.GetString("UnrecognizedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version detected:.
        /// </summary>
        internal static string UnsupportedVersion {
            get {
                return ResourceManager.GetString("UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty:.
        /// </summary>
        internal static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative:.
        /// </summary>
        internal static string ValueCannotBeNegative {
            get {
                return ResourceManager.GetString("ValueCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be zero or negative:.
        /// </summary>
        internal static string ValueCannotBeNegativeOrZero {
            get {
                return ResourceManager.GetString("ValueCannotBeNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be parsed:.
        /// </summary>
        internal static string ValueCannotBeParsed {
            get {
                return ResourceManager.GetString("ValueCannotBeParsed", resourceCulture);
            }
        }
    }
}
