//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainVision.Lab.FileFormats.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainVision.Lab.FileFormats.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Conversion to BIDS failed:.
    /// </summary>
    internal static string ConsoleOutputConversionFailed {
        get {
            return ResourceManager.GetString("ConsoleOutputConversionFailed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid syntax:.
    /// </summary>
    internal static string ConsoleOutputInvalidSyntax {
        get {
            return ResourceManager.GetString("ConsoleOutputInvalidSyntax", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unexpected error:.
    /// </summary>
    internal static string ConsoleOutputUnexpectedError {
        get {
            return ResourceManager.GetString("ConsoleOutputUnexpectedError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected one of:.
    /// </summary>
    internal static string ExceptionTextExpectedEnum {
        get {
            return ResourceManager.GetString("ExceptionTextExpectedEnum", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected floating point number.
    /// </summary>
    internal static string ExceptionTextExpectedFloat {
        get {
            return ResourceManager.GetString("ExceptionTextExpectedFloat", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected one of valid options or empty.
    /// </summary>
    internal static string ExceptionTextExpectedValidOptionOrEmpty {
        get {
            return ResourceManager.GetString("ExceptionTextExpectedValidOptionOrEmpty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter already set:.
    /// </summary>
    internal static string ExceptionTextParamDuplicated {
        get {
            return ResourceManager.GetString("ExceptionTextParamDuplicated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter value cannot be empty:.
    /// </summary>
    internal static string ExceptionTextParamEmpty {
        get {
            return ResourceManager.GetString("ExceptionTextParamEmpty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unrecognized parameter:.
    /// </summary>
    internal static string ExceptionTextParamUnrecognized {
        get {
            return ResourceManager.GetString("ExceptionTextParamUnrecognized", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter has missing value:.
    /// </summary>
    internal static string ExceptionTextParamValueMissing {
        get {
            return ResourceManager.GetString("ExceptionTextParamValueMissing", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter value unrecognized:.
    /// </summary>
    internal static string ExceptionTextParamValueUnrecognized {
        get {
            return ResourceManager.GetString("ExceptionTextParamValueUnrecognized", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Parameter value cannot be zero or negative:.
    /// </summary>
    internal static string ExceptionTextParamZeroOrNegative {
        get {
            return ResourceManager.GetString("ExceptionTextParamZeroOrNegative", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Required parameter missing:.
    /// </summary>
    internal static string ExceptionTextRequiredParamMissing {
        get {
            return ResourceManager.GetString("ExceptionTextRequiredParamMissing", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to List of contributors to the study.\n[default: field is not created]\nOPTIONAL field for the dataset_description.json file..
    /// </summary>
    internal static string HelpMessageAuthors {
        get {
            return ResourceManager.GetString("HelpMessageAuthors", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Name of the dataset.\n[default: empty]\nREQUIRED field for the dataset_description.json file.\nDetailed description of the study shall be provided by the user\nin the README file, found under the root directory of a BIDS dataset.\nFurther modifications after the creation of the BIDS dataset\nshall be entered manually in the CHANGES file,\nfound under the root directory of a BIDS dataset..
    /// </summary>
    internal static string HelpMessageDataset {
        get {
            return ResourceManager.GetString("HelpMessageDataset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Path to store the converted files..
    /// </summary>
    internal static string HelpMessageDst {
        get {
            return ResourceManager.GetString("HelpMessageDst", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Description of the reference scheme and (when applicable) location of the recording reference electrode.\nE.g.: “unipolar reference placed at Cz”, “left mastoid (M1)”, ...\n[default: Unknown]\nREQUIRED field for the *_eeg.json file..
    /// </summary>
    internal static string HelpMessageEegReference {
        get {
            return ResourceManager.GetString("HelpMessageEegReference", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional general purpose parameters:.
    /// </summary>
    internal static string HelpMessageGeneralPurposeParams {
        get {
            return ResourceManager.GetString("HelpMessageGeneralPurposeParams", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Display brief description of all available parameters or detailed description for a particular parameter..
    /// </summary>
    internal static string HelpMessageHelp {
        get {
            return ResourceManager.GetString("HelpMessageHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Type of license for distributing the dataset (e.g., PD, PDDL, CCO).\n[default: field is not created]\nRECOMMENDED field for the dataset_description.json file..
    /// </summary>
    internal static string HelpMessageLicense {
        get {
            return ResourceManager.GetString("HelpMessageLicense", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to EEG device manufacturer.\n[default: Brain Products]\nRECOMMENDED field for the *_eeg.json file..
    /// </summary>
    internal static string HelpMessageManufacturer {
        get {
            return ResourceManager.GetString("HelpMessageManufacturer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional parameters:.
    /// </summary>
    internal static string HelpMessageOptionalParams {
        get {
            return ResourceManager.GetString("HelpMessageOptionalParams", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to optional-parameters.
    /// </summary>
    internal static string HelpMessageOptionalParamsInCommandline {
        get {
            return ResourceManager.GetString("HelpMessageOptionalParamsInCommandline", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Frequency of the power grid at the geographical location of the recording setup.\n[default: 50]\nREQUIRED field for the *_eeg.json file..
    /// </summary>
    internal static string HelpMessagePowerLineFreq {
        get {
            return ResourceManager.GetString("HelpMessagePowerLineFreq", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Required parameters:.
    /// </summary>
    internal static string HelpMessageRequiredParams {
        get {
            return ResourceManager.GetString("HelpMessageRequiredParams", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to required-parameters.
    /// </summary>
    internal static string HelpMessageRequiredParamsInCommandline {
        get {
            return ResourceManager.GetString("HelpMessageRequiredParamsInCommandline", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Label to group files recorded in a given session for a given participant.\n[default: single session].
    /// </summary>
    internal static string HelpMessageSession {
        get {
            return ResourceManager.GetString("HelpMessageSession", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Path to and name of the BrainVision header file (*.vhdr)..
    /// </summary>
    internal static string HelpMessageSrc {
        get {
            return ResourceManager.GetString("HelpMessageSrc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Label/ID of participant in the study.\n[default: auto-incremented 2-digit number (sub-01, sub-02, ...)].
    /// </summary>
    internal static string HelpMessageSubject {
        get {
            return ResourceManager.GetString("HelpMessageSubject", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Name of the activity performed by the participant.\n[default: &lt;input_filename&gt;]\nREQUIRED field for the *_eeg.json file..
    /// </summary>
    internal static string HelpMessageTask {
        get {
            return ResourceManager.GetString("HelpMessageTask", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Usage:.
    /// </summary>
    internal static string HelpMessageUsage {
        get {
            return ResourceManager.GetString("HelpMessageUsage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Display application version..
    /// </summary>
    internal static string HelpMessageVersion {
        get {
            return ResourceManager.GetString("HelpMessageVersion", resourceCulture);
        }
    }
}
